defmodule DroneFeedWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :drone_feed

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {DroneFeedWeb.SessionCookie, :session_options, []}]],
    longpoll: [connect_info: [session: {DroneFeedWeb.SessionCookie, :session_options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :drone_feed,
    gzip: not code_reloading?,
    only: DroneFeedWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :drone_feed
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session
  plug DroneFeedWeb.Router

  defp session(conn, _opts) do
    opts = Plug.Session.init(DroneFeedWeb.SessionCookie.session_options())
    Plug.Session.call(conn, opts)
  end
end
