import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :drone_feed, DroneFeedWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # TLS terminates at Caddy; trust X-Forwarded-Proto and redirect plain HTTP.
  force_ssl: [rewrite_on: [:x_forwarded_proto], hsts: true]

# Do not print debug messages in production
config :logger, level: :info

# SMTP is configured at runtime from env (see runtime.exs).
config :swoosh, api_client: false
