defmodule DroneFeed.Locations do
  @moduledoc """
  Curated place names for location typeahead ("City, Region/Country").
  Free-text entry is still allowed; this list only powers suggestions.
  """

  @places [
    "Aberdeen, Scotland",
    "Abu Dhabi, UAE",
    "Accra, Ghana",
    "Adelaide, Australia",
    "Albuquerque, NM",
    "Alexandria, VA",
    "Algiers, Algeria",
    "Amman, Jordan",
    "Amsterdam, Netherlands",
    "Anchorage, AK",
    "Ankara, Turkey",
    "Ann Arbor, MI",
    "Antwerp, Belgium",
    "Arlington, VA",
    "Athens, Greece",
    "Atlanta, GA",
    "Auckland, New Zealand",
    "Austin, TX",
    "Baghdad, Iraq",
    "Baltimore, MD",
    "Bangkok, Thailand",
    "Barcelona, Spain",
    "Basel, Switzerland",
    "Beijing, China",
    "Beirut, Lebanon",
    "Belfast, Northern Ireland",
    "Belgrade, Serbia",
    "Bergen, Norway",
    "Berlin, Germany",
    "Bern, Switzerland",
    "Birmingham, AL",
    "Birmingham, England",
    "Bogotá, Colombia",
    "Boston, MA",
    "Boulder, CO",
    "Brasília, Brazil",
    "Brisbane, Australia",
    "Bristol, England",
    "Brussels, Belgium",
    "Bucharest, Romania",
    "Budapest, Hungary",
    "Buenos Aires, Argentina",
    "Buffalo, NY",
    "Cairo, Egypt",
    "Calgary, Canada",
    "Cambridge, England",
    "Cambridge, MA",
    "Canberra, Australia",
    "Cape Town, South Africa",
    "Caracas, Venezuela",
    "Cardiff, Wales",
    "Charleston, SC",
    "Charlotte, NC",
    "Chennai, India",
    "Chicago, IL",
    "Cincinnati, OH",
    "Cleveland, OH",
    "Cologne, Germany",
    "Colorado Springs, CO",
    "Columbia, SC",
    "Columbus, OH",
    "Copenhagen, Denmark",
    "Cork, Ireland",
    "Dallas, TX",
    "Dayton, OH",
    "Denver, CO",
    "Detroit, MI",
    "Doha, Qatar",
    "Dresden, Germany",
    "Dublin, Ireland",
    "Durham, NC",
    "Edinburgh, Scotland",
    "Edmonton, Canada",
    "Eindhoven, Netherlands",
    "Fairbanks, AK",
    "Florence, Italy",
    "Fort Collins, CO",
    "Fort Worth, TX",
    "Frankfurt, Germany",
    "Fukuoka, Japan",
    "Geneva, Switzerland",
    "Glasgow, Scotland",
    "Gothenburg, Sweden",
    "Grenoble, France",
    "Guadalajara, Mexico",
    "Guangzhou, China",
    "Halifax, Canada",
    "Hamburg, Germany",
    "Hanoi, Vietnam",
    "Hanover, Germany",
    "Helsinki, Finland",
    "Hiroshima, Japan",
    "Ho Chi Minh City, Vietnam",
    "Hong Kong",
    "Honolulu, HI",
    "Houston, TX",
    "Huntsville, AL",
    "Hyderabad, India",
    "Indianapolis, IN",
    "Irvine, CA",
    "Istanbul, Turkey",
    "Jakarta, Indonesia",
    "Jerusalem, Israel",
    "Johannesburg, South Africa",
    "Kansas City, MO",
    "Karlsruhe, Germany",
    "Kathmandu, Nepal",
    "Kiev, Ukraine",
    "Kingston, Jamaica",
    "Knoxville, TN",
    "Kraków, Poland",
    "Kuala Lumpur, Malaysia",
    "Kuwait City, Kuwait",
    "Kyoto, Japan",
    "Lagos, Nigeria",
    "Las Vegas, NV",
    "Lausanne, Switzerland",
    "Leeds, England",
    "Leipzig, Germany",
    "Lima, Peru",
    "Lisbon, Portugal",
    "Liverpool, England",
    "Ljubljana, Slovenia",
    "London, England",
    "Los Alamos, NM",
    "Los Angeles, CA",
    "Louisville, KY",
    "Luxembourg City, Luxembourg",
    "Lyon, France",
    "Madison, WI",
    "Madrid, Spain",
    "Manchester, England",
    "Manila, Philippines",
    "Melbourne, Australia",
    "Memphis, TN",
    "Mexico City, Mexico",
    "Miami, FL",
    "Milan, Italy",
    "Milwaukee, WI",
    "Minneapolis, MN",
    "Minsk, Belarus",
    "Monterey, CA",
    "Montreal, Canada",
    "Moscow, Russia",
    "Mumbai, India",
    "Munich, Germany",
    "Nairobi, Kenya",
    "Nanjing, China",
    "Naples, Italy",
    "Nashville, TN",
    "New Delhi, India",
    "New Haven, CT",
    "New Orleans, LA",
    "New York, NY",
    "Newcastle, England",
    "Nice, France",
    "Norfolk, VA",
    "Nottingham, England",
    "Nuremberg, Germany",
    "Oakland, CA",
    "Oklahoma City, OK",
    "Omaha, NE",
    "Orlando, FL",
    "Osaka, Japan",
    "Oslo, Norway",
    "Ottawa, Canada",
    "Oxford, England",
    "Palo Alto, CA",
    "Panama City, Panama",
    "Paris, France",
    "Pasadena, CA",
    "Perth, Australia",
    "Philadelphia, PA",
    "Phoenix, AZ",
    "Pittsburgh, PA",
    "Portland, OR",
    "Porto, Portugal",
    "Prague, Czechia",
    "Princeton, NJ",
    "Providence, RI",
    "Pune, India",
    "Quebec City, Canada",
    "Quito, Ecuador",
    "Raleigh, NC",
    "Reykjavik, Iceland",
    "Richmond, VA",
    "Riga, Latvia",
    "Rio de Janeiro, Brazil",
    "Riyadh, Saudi Arabia",
    "Rome, Italy",
    "Rotterdam, Netherlands",
    "Sacramento, CA",
    "Salt Lake City, UT",
    "San Antonio, TX",
    "San Diego, CA",
    "San Francisco, CA",
    "San Jose, CA",
    "San Juan, PR",
    "Santiago, Chile",
    "São Paulo, Brazil",
    "Sapporo, Japan",
    "Seattle, WA",
    "Seoul, South Korea",
    "Seville, Spain",
    "Shanghai, China",
    "Sheffield, England",
    "Shenzhen, China",
    "Singapore",
    "Sofia, Bulgaria",
    "Southampton, England",
    "St. Louis, MO",
    "Stanford, CA",
    "Stockholm, Sweden",
    "Stuttgart, Germany",
    "Sydney, Australia",
    "Taipei, Taiwan",
    "Tallahassee, FL",
    "Tallinn, Estonia",
    "Tampa, FL",
    "Tehran, Iran",
    "Tel Aviv, Israel",
    "Thessaloniki, Greece",
    "Tokyo, Japan",
    "Toronto, Canada",
    "Toulouse, France",
    "Tucson, AZ",
    "Turin, Italy",
    "Uppsala, Sweden",
    "Utrecht, Netherlands",
    "Valencia, Spain",
    "Vancouver, Canada",
    "Venice, Italy",
    "Vienna, Austria",
    "Vilnius, Lithuania",
    "Virginia Beach, VA",
    "Warsaw, Poland",
    "Washington, DC",
    "Wellington, New Zealand",
    "Winnipeg, Canada",
    "Wuhan, China",
    "Zürich, Switzerland"
  ]

  @doc "All curated place labels."
  def all, do: @places

  @doc """
  Returns up to `limit` places whose label contains `query` (case-insensitive).
  Empty queries return no suggestions so the list stays out of the way.
  """
  def suggest(query, limit \\ 8)

  def suggest(query, limit) when is_binary(query) do
    trimmed = String.trim(query)

    if String.length(trimmed) < 1 do
      []
    else
      needle = String.downcase(trimmed)

      @places
      |> Enum.filter(&(String.downcase(&1) |> String.contains?(needle)))
      |> Enum.take(limit)
    end
  end

  def suggest(_, _), do: []
end
